require "colorize"
require "sxp"

require_relative "./nanga/code"
require_relative "./nanga/generic_lexer"
require_relative "./nanga/generic_parser"

require_relative "./nanga/version"
require_relative "./nanga/runner"
require_relative "./nanga/compiler"
require_relative "./nanga/lexer"
require_relative "./nanga/parser"
require_relative "./nanga/visitor"
require_relative "./nanga/pretty_printer"
require_relative "./nanga/ast"
require_relative "./nanga/open_classes"
require_relative "./nanga/emitter"
require_relative "./nanga/resolver"
require_relative "./nanga/ir_gen"
require_relative "./nanga/range_propagator"
require_relative "./nanga/strength_reductor"
require_relative "./nanga/dfg"
require_relative "./nanga/dfg_gen"
require_relative "./nanga/dfg_printer"
